model_name: "DeepSeek/DeepSeek-V3-Lite"
model_path: "/home/scratch.trt_llm_data/llm-models/DeepSeek-V3-Lite/nvfp4_moe_only"
tensor_parallel_size: 2
moe_expert_parallel_size: 2
enable_attention_dp: false
max_num_tokens: 10240
max_batch_size: 16
trust_remote_code: true

kv_cache_config:
  free_gpu_memory_fraction: 0.95

pytorch_backend_config:
  enable_overlap_scheduler: true
  use_cuda_graph: true