# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# In the case of disaggregated deployment, this config will apply to each server
# and will be overwritten by the disaggregated config file

# NOTE: FP4 can fit on GB200 (4xB200 GPUs)
# For other precisions like FP8 or FP16, you'll need to adjust
# the number of GPUs/parallelism according to your hardware.
model_name: "deepseek-ai/DeepSeek-R1-FP4"
tensor_parallel_size: 4
moe_expert_parallel_size: 4
max_num_tokens: 8192
max_batch_size: 16
backend: pytorch

kv_cache_config:
  free_gpu_memory_fraction: 0.80

pytorch_backend_config:
  # must be false for disagg, can be true for agg
  enable_overlap_scheduler: false
  use_cuda_graph: true
