version: '3'
services:
  dynamo:
    image: dynamo:latest-vllm
    volumes:
      - /tmp:/tmp
      - /mnt:/mnt
      - ../:/workspace
      - ${HF_HOME:-$HOME/.cache/huggingface}:/root/.cache/huggingface
    working_dir: /workspace
    network_mode: host
    ipc: host
    cap_add:
      - SYS_PTRACE
    shm_size: 10G
    command: sleep infinity
    ulimits:
      memlock: -1
      stack: 67108864
    privileged: true
    environment:
      - HF_TOKEN
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]