hostname: localhost
port: 8080
trust_remote_code: true
backend: pytorch

context_servers:
  num_instances: 1
  tensor_parallel_size: 1
  kv_cache_config:
    free_gpu_memory_fraction: 0.85
    enable_block_reuse: false
  pytorch_backend_config:
    enable_overlap_scheduler: false
    use_cuda_graph: true
  urls:
      - "localhost:8001"

generation_servers:
  num_instances: 1
  tensor_parallel_size: 1
  kv_cache_config:
    free_gpu_memory_fraction: 0.90
    enable_block_reuse: false
  pytorch_backend_config:
    enable_overlap_scheduler: true
    use_cuda_graph: true
  urls:
      - "localhost:8002"
